services:
  ob:
    build: .
    volumes:
      - ./ob-vault:/vault
      - ob-config:/config
    stdin_open: true
    tty: true

  sync:
    build: .
    volumes:
      - ./ob-vault:/vault
      - ob-config:/config
    command: sync --continuous
    restart: unless-stopped

volumes:
  ob-config:
